// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

#include <string>
#include <vector>

#include "ark/file_io.h"
#include "ark/include/ark.h"
#include "ark/logging.h"

using namespace std;

namespace ark {

/// @brief Initialize the ARK runtime.
///
/// This function should be called by the user before any other functions are
/// called. It is safe to call this function multiple times.
void init()
{
    // Clean up the shared memory directory. This is useful when the previous
    // run crashed, as this forces to remove locks generated by previous runs.
    // This may crash other ARK processes running on the same machine, if there
    // are any.
    vector<string> paths = list_dir("/dev/shm");
    for (auto &path : paths) {
        if (path.substr(0, 4) == "ark.") {
            if (remove_file(path) != 0) {
                LOGERR("init failed: failed to remove ", path, " (errno ",
                       errno, ")");
            }
        }
    }
}

} // namespace ark
