#include <string>
#include <vector>

#include "ark/file_io.h"
#include "ark/init.h"

using namespace std;

namespace ark {

// Clean up the shared memory directory. This is useful when the previous run
// crashed, as this forces to remove locks generated by previous runs.
// This may crash other ARK processes running on the same machine, if there are
// any.
void init()
{
    vector<string> paths = list_dir("/dev/shm");
    for (auto &path : paths) {
        if (path.substr(0, 4) == "ark.") {
            remove_file(path);
        }
    }
}

} // namespace ark
