trigger:
- main

pr:
  branches:
    include:
    - main
  drafts: false

jobs:
- job: UnitTest
  timeoutInMinutes: 30
  pool:
    name: mscclpp
  strategy:
    matrix:
      cuda11:
        containerImage: ghcr.io/microsoft/ark/ark:base-cuda11.8
      cuda12:
        containerImage: ghcr.io/microsoft/ark/ark:base-cuda12.1

  container:
    image: $[ variables['containerImage'] ]
    options: --privileged --ipc=host --gpus=all --ulimit memlock=-1:-1

  steps:
  - task: Bash@3
    name: Build
    displayName: Build
    inputs:
      targetType: 'inline'
      script: |
        echo "Building"
      workingDirectory: '$(System.DefaultWorkingDirectory)'
