name: Lint

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ main ]

jobs:
  linters:
    runs-on: ubuntu-20.04

    steps:
    - name: Check git version
      env:
        min-ver: "2.18"
      run: dpkg --compare-versions $(git version | awk '{print $3}') ge ${{ env.min-ver }}

    - name: Check out Git repository
      uses: actions/checkout@v3

    - name: Install ClangFormat
      run: sudo apt-get install -y clang-format-12

    - name: Run cpplint
      run: make cpplint

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: python3.8 -m pip install black

    - name: Run linters
      uses: wearerequired/lint-action@v2
      with:
        black: true
        black_auto_fix: false
        black_args: "--config .black --check"

  spelling:
    runs-on: ubuntu-20.04

    steps:
    - name: Check git version
      env:
        min-ver: "2.18"
      run: dpkg --compare-versions $(git version | awk '{print $3}') ge ${{ env.min-ver }}

    - name: Check out Git repository
      uses: actions/checkout@v3

    - name: Download misspell
      run: |
        curl -L https://github.com/client9/misspell/releases/download/v0.3.4/misspell_0.3.4_linux_64bit.tar.gz -o /tmp/misspell_0.3.4_linux_64bit.tar.gz
        tar -xzf /tmp/misspell_0.3.4_linux_64bit.tar.gz -C .

    - name: Check spelling
      run: |
        ./misspell -error .github ark examples python scripts
